# Generated by Django 5.1.1 on 2024-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_fund', '0006_alter_deduction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='category',
            field=models.CharField(choices=[('इमाम साहब की सैलरी में', 'इमाम साहब की सैलरी में'), ('मस्जिद में खर्च', 'मस्जिद में खर्च'), ('चालू खर्च', 'चालू खर्च')], max_length=30),
        ),
    ]
