# Generated by Django 5.1.1 on 2024-09-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_fund', '0007_alter_deduction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_collected',
        ),
    ]
